[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia = "", arb-sepolia = "" }

remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@ccip/=lib/ccip/',
    '@chainlink-local/=lib/chainlink-local/',
]
